name: React

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gui
      CI: ""
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: yarn install
        working-directory: ${{env.working-directory}}

      - name: Build Site
        run: yarn build
        working-directory: ${{env.working-directory}}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            gui/dist
